### ISSUE TITLE
Typescript in RunKit?

### ISSUE THREAD

**Issue by pcktlwyrcode** [zwakheid/deepl-client#20]
Is typescript so prevalent that a non-typescript version isnt also made available?

**Comment by zwakheid** [comment]
Typescript transpiles to javascript, so you should be able to use it in a javascript project without any issues.

**Comment by pcktlwyrcode** [comment]
Ok thanks but I wanted to test it first on RunKit. Not possible?

**Comment by zwakheid** [comment]
I've never used RunKit before, but it should work considering they advertise having access to every npm package.
